/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class reglib_NativeRegistry */

#ifndef _Included_reglib_NativeRegistry
#define _Included_reglib_NativeRegistry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     reglib_NativeRegistry
 * Method:    openKey
 * Signature: (ILjava/lang/String;)Lreglib/Handle;
 */
JNIEXPORT jobject JNICALL Java_reglib_NativeRegistry_openKey
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     reglib_NativeRegistry
 * Method:    createKey
 * Signature: (ILjava/lang/String;)Lreglib/Handle;
 */
JNIEXPORT jobject JNICALL Java_reglib_NativeRegistry_createKey
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
